openapi: 3.0.3
info:
  title: Portfolio API
  version: 1.0.0
  description: Public REST API for retrieving portfolio projects and their associated
    details.
paths:
  /api/v1/contacts/add/:
    post:
      operationId: addContact
      description: Add a new contact to the databaseAnd send an email message to the
        portfolio admin.
      summary: Add a new contact and message admin
      tags:
      - Contact
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContactRequest'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'
          description: A new contact instance has been created.
  /api/v1/projects/:
    get:
      operationId: projectsList
      description: List all portfolio projects with their details.
      summary: List projects
      tags:
      - Projects
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Project'
          description: A list of portfolio projects.
  /api/v1/projects/{uuid}/:
    get:
      operationId: projectsRetrieve
      description: Retrieve a single portfolio project by UUID.
      summary: Retrieve a project
      parameters:
      - in: path
        name: uuid
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - Projects
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
          description: The requested portfolio project.
components:
  schemas:
    Challenge:
      type: object
      properties:
        title:
          type: string
          maxLength: 160
        description:
          type: string
      required:
      - description
      - title
    Contact:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 300
        email:
          type: string
          format: email
          maxLength: 500
        message:
          type: string
          maxLength: 10000
        date_added:
          type: string
          format: date-time
      required:
      - email
      - id
      - message
      - name
    ContactRequest:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 300
        email:
          type: string
          format: email
          minLength: 1
          maxLength: 500
        message:
          type: string
          minLength: 1
          maxLength: 10000
        date_added:
          type: string
          format: date-time
      required:
      - email
      - message
      - name
    Detail:
      type: object
      properties:
        problem:
          type: string
        solution:
          type: string
        front_end_techs:
          type: string
          maxLength: 160
        back_end_techs:
          type: string
          maxLength: 160
        other_techs:
          type: string
          maxLength: 160
        key_features:
          type: array
          items:
            $ref: '#/components/schemas/KeyFeature'
        challenges:
          type: array
          items:
            $ref: '#/components/schemas/Challenge'
        impacts:
          type: array
          items:
            $ref: '#/components/schemas/Impact'
      required:
      - back_end_techs
      - challenges
      - front_end_techs
      - impacts
      - key_features
      - other_techs
      - problem
      - solution
    Feature:
      type: object
      properties:
        name:
          type: string
          maxLength: 60
      required:
      - name
    Impact:
      type: object
      properties:
        title:
          type: string
          maxLength: 160
        description:
          type: string
      required:
      - description
      - title
    Industry:
      type: object
      properties:
        name:
          type: string
          maxLength: 160
      required:
      - name
    KeyFeature:
      type: object
      properties:
        title:
          type: string
          maxLength: 160
        description:
          type: string
      required:
      - description
      - title
    Project:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
          maxLength: 100
        short_description:
          type: string
          maxLength: 160
        long_description:
          type: string
        snapshot:
          type: string
          format: uri
          nullable: true
          readOnly: true
        industry:
          $ref: '#/components/schemas/Industry'
        technologies:
          type: array
          items:
            $ref: '#/components/schemas/Technology'
        features:
          type: array
          items:
            $ref: '#/components/schemas/Feature'
        is_featured:
          type: boolean
        live_site:
          type: string
          format: uri
          maxLength: 200
        github_url:
          type: string
          format: uri
          maxLength: 200
        first_created:
          type: string
          format: date
        date_added:
          type: string
          format: date-time
          readOnly: true
        details:
          $ref: '#/components/schemas/Detail'
      required:
      - date_added
      - details
      - features
      - first_created
      - github_url
      - industry
      - live_site
      - long_description
      - name
      - short_description
      - snapshot
      - technologies
      - uuid
    Technology:
      type: object
      properties:
        name:
          type: string
          maxLength: 60
      required:
      - name
